on: push
name: npm build, lint, test and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/checkout@v2
        with:
          args: install
      - name: npm test
        uses: actions/checkout@v2
        with:
          args: run test
      - name: npm lint
        uses: actions/checkout@v2
        with:
          args: run lint
      - name: docker build
        uses: actions/checkout@v2
        with:
          args: build -t secalquin/nodejs .
      - name: docker login
        uses: actions/checkout@v2
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: docker push
        uses: actions/checkout@v2
        with:
          args: push secalquin/nodejs
